apiVersion: v1
kind: Secret
metadata:
    name: test-team-auth
    namespace: apps
stringData:
    password: ENC[AES256_GCM,data:j/bS/BEl70lg14OfFgQV7+8rhI1k/B7i6rqM4FkIAw735cndRiwRng==,iv:dsrTr5MzmsyZL+c3qsPPVW8xkf/7klPGCMPm2KmtpFo=,tag:WV+v9TcVF2p+OM+lyOuvYw==,type:str]
    username: ENC[AES256_GCM,data:kpVnpYfubrb3ig==,iv:Yl/14fWMMCiQGUXpz+FZI7kVnIH1AncrzfMFNm0p5Ng=,tag:b/c+wKz8JXMLcYxId9m3hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-12T10:06:02Z"
    mac: ENC[AES256_GCM,data:frIQMmKIvOK+RM749mfYrHvMU4FYHZZZVdO1hK87RGVyJeMbgx49809HVuTeet/sqoG04xlm5zIOywxT/syi0bfYmXT+Ong96A0ebkSi5TO3gXtkX7hUaj/F8UtixVHjjMNOxFKO1Au3gXVsV9P8qe2AX+sg5vak18jl/zzcmT4=,iv:Rpj11J14Htrx0NTIhpwzj4QCGhkpZX/mQfsToaZ9joY=,tag:pgDkNVcpgawa4vz3eW76qA==,type:str]
    pgp:
        - created_at: "2021-04-12T10:06:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA5DM4V+xSyTtAQgAWoHEXVMjmMJduT1ds4DRoc/PuAvyCpPPdE+gQ+u1oyfi
            GakuJgIcr1bcRgCXuiPcU8r1eGIpOUlwdHTimQHU+egKRA+3uznR1x0nL9MRUvNc
            lgZrztkzDBaWscqr7udlsYQQsvDADabU2EPPjsU1g8Q1AwPd1nRIzh2xe9DyQln2
            Fd0iBGQRjvgL5J4Akkcaar127eRJ7GKXBly+ApmNIfHHPe3XJr2xAa2STuLqfk0t
            YQR4oIDmxV5gLoOpHMESsRKgfLLcOr/J6lqpp+OQcUnVQmQYZdNtt9CMTeqvb6N/
            7muxxjlQ0bYiInfAopsFuvFt/ucz4ZBLqBN2TQg249LmAWcVoP+CLFAX5PuFT1CE
            taHqeoy3md6s+7x+iA0Nhsr+Q+NOGSNLEKchE350rfIbJCHTNlaCJDwJt1DSFgva
            weShb268R88KIglaMuS3mT184vUBoE4A
            =2W3+
            -----END PGP MESSAGE-----
          fp: 4724B1E3D2FA46F0C4B8ED2C93098C4CBFAFC2BE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
