apiVersion: v1
kind: Secret
metadata:
    name: test-team-auth
    namespace: test
stringData:
    password: ENC[AES256_GCM,data:Br4vPZ3vqjeqK8uQJN1L5Zgf5SQgXUo6Y5LFGvZt1qldlCtoAw/6Xw==,iv:oRdRHUqgn0HYykYwtmqhXAQK/ZhAf12jCJw6CCyWEsw=,tag:yFLol4I9JnvGh1mjHOvLTg==,type:str]
    username: ENC[AES256_GCM,data:6y6hWd5Oy/cJNg==,iv:5Ub9h37uyvFNQLvLBB4KgHTs/8XU/7VmNQsQJOIIYpE=,tag:kklB0adlDjI/5dWYiwH3rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-12T12:11:42Z"
    mac: ENC[AES256_GCM,data:xzWEejsGuiY2dkBJf0YM3uV0/W8WJgbX8phB4S+/ofXorL9R+EM9UZ82banSpu6SsHWSRdqk+hfF4qVnCiOLEG0hxwLU+SZQZfpctQmm9n/goXSMkbDtYTds1fZYjeDQ1pAqXh/sCflb5tuJddzXau3/SG1P+pPz3nXV4a+XTuY=,iv:Mm724q46c3B9u8Lrpha/uOhYFpdm7nPdD5zCPd1L2rw=,tag:NuFjU9+fg+vjTio6Xj2nZg==,type:str]
    pgp:
        - created_at: "2021-04-12T12:11:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA5DM4V+xSyTtAQgABjN3t5Il94jCJyxeToQ+z4Kg+YpepqMJVY/fpVqInOfX
            jIZSTzYLBhENy2GociOJKS0pZ/dZuE2kOrpHS45Au/G5fAWUBmASXuwqTY90pe+3
            aKQkrZqWHoPclJI8RYtTxhGt/QG2E7dmwSdzHWBieUHuArESFZTxQkkFAgKETNdJ
            kLBgpfc4GtXDABQ6neeyMGtFpyX+c+Y8Vf9EhYf0QJcfpGdwlpbH+6+cZEMdQt7R
            NzggZsjupn5cR6TXop2CAjlE7j1oDamuPmfGkLD4K/IqZDxPv0ULJRJq2A3j+l8R
            DaOd1J6SQo+zszGuG6mLi+fOcybxxQjkGB8cDbSJ99LmASWO9Zpxca+s9ZB9V5oo
            QL4wUl4j2XKUSe9rXJPbI3nQU+b/HMuevSLf8Uc602P5TGBlXFeaTD7mVZwMneOf
            2OQ7pB6mmTGVSZrWn3AULmaU4jDLqDYA
            =Df3I
            -----END PGP MESSAGE-----
          fp: 4724B1E3D2FA46F0C4B8ED2C93098C4CBFAFC2BE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
