---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: test-team
  namespace: test
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: test-team-auth
  url: https://github.com/klemo-rono/flux-test.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-team
  namespace: test
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: test-team
  sourceRef:
    kind: GitRepository
    name: test-team

